model = "QuartzNet"
[[block]]
filters = 303
repeat = 1
kernel = [ 69,]
stride = [ 3,]
dilation = [ 1,]
dropout = 0.0
residual = false
separable = false

[[block]]
filters = 52
repeat = 8
kernel = [ 21,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = true
separable = true

[[block]]
filters = 31
repeat = 4
kernel = [ 69,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = true
separable = true

[[block]]
filters = 54
repeat = 5
kernel = [ 81,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = true
separable = true

[[block]]
filters = 51
repeat = 1
kernel = [ 55,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = true
separable = true

[[block]]
filters = 53
repeat = 8
kernel = [ 17,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = true
separable = true

[[block]]
filters = 140
repeat = 1
kernel = [ 53,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = false
separable = true

[[block]]
filters = 380
repeat = 1
kernel = [ 1,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = false
separable = false

[labels]
labels = [ "N", "A", "C", "G", "T",]

[input]
features = 1

[encoder]
activation = "gelu"
