model = "QuartzNet"
[[block]]
filters = 336
repeat = 1
kernel = [ 61,]
stride = [ 3,]
dilation = [ 1,]
dropout = 0.0
residual = false
separable = false

[[block]]
filters = 66
repeat = 8
kernel = [ 37,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = true
separable = true

[[block]]
filters = 82
repeat = 1
kernel = [ 87,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = true
separable = true

[[block]]
filters = 67
repeat = 5
kernel = [ 81,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = true
separable = true

[[block]]
filters = 50
repeat = 3
kernel = [ 25,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = true
separable = true

[[block]]
filters = 52
repeat = 7
kernel = [ 1,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = true
separable = true

[[block]]
filters = 155
repeat = 1
kernel = [ 63,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = false
separable = true

[[block]]
filters = 411
repeat = 1
kernel = [ 1,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.0
residual = false
separable = false

[labels]
labels = [ "N", "A", "C", "G", "T",]

[input]
features = 1

[encoder]
activation = "gelu"
